--1.
SELECT STUDENT_NO 학번,STUDENT_NAME 이름,
TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 3;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!= '3';

--3
SELECT PROFESSOR_NAME 교수이름,
    FLOOR(MONTHS_BETWEEN(SYSDATE,19||SUBSTR(PROFESSOR_SSN,1,6))/12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 2 ;

--4
SELECT 
    CASE 
        WHEN LENGTH(PROFESSOR_NAME) =2 THEN SUBSTR(PROFESSOR_NAME, -1)
        ELSE SUBSTR(PROFESSOR_NAME, -2)
        END 이름
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
--WHERE FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'))/12) > 19 ;
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD')) >19;
--6
SELECT TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DY') 
FROM DUAL;


--7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY"년"MM"월"DD"일"')"1번",
    TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY"년"MM"월"DD"일"')"2번",
    
    TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'),'RRRR"년"MM"월"DD"일"')"3번",
    TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'RRRR"년"MM"월"DD"일"')"4번"
    
FROM DUAL;

-- 8
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

-- 9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


