-- 오라클 18c 버전
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER test_kdh IDENTIFIED BY test1234;

ALTER USER test_kdh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO test_kdh;