-- 오라클 18c 버전
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER community_kdh IDENTIFIED BY community1234;

ALTER USER community_kdh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO community_kdh;