-- 암호화 된 비밀번호로 업데이트 
UPDATE MEMBER SET 
MEMBER_PW = 'aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg=='
WHERE MEMBER_NO = '1';


-- MEMBER TABLE 비밀번호 컬럼 크기 변경
ALTER TABLE MEMBER 
MODIFY MEMBER_PW VARCHAR2(100);

COMMIT;


